[package]
name = "reputation-net"
version = "0.1.0"
authors = ["Hans-Martin Mosner <hmm@heeg.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# libp2p = { git = "https://github.com/libp2p/rust-libp2p.git" }
libp2p = "0.39"
futures = "*"
cidr = "*"
sha2 = "*"
chrono = { version = "*", features = ["clock"] }
base64 = "*"
async-std = { version = "*", features = ["attributes"] }
once_cell = "*"
libsqlite3-sys = "*"
sqlx = { version = "*", features = ["runtime-async-std-rustls", "sqlite"] }
percent-encoding = "*"
nom = "7.0"
env_logger = "*"
log = "*"