contact = "please visit http://postmaster.example.com"


# Reject mail coming directly from dynamic IP ranges
[rules.reject_dynamic]
field = ["connect.client-addr", "connect.client-name"]
match = { reputation = "dynamic" }
reject = "Mail from dynamic network range"

# Reject mail associated with spammers (reputation-net)
[rules.reject_spammer]
field = [
    "connect.client-addr",
    "connect.client-name",
    "header.from",
    "header.reply-to",
    "header.sender",
    "header.received.domain",
    "header.received.ipv4",
]
match = { reputation = "spammer" }
reject = "Listed as spam source"

# Handle mail associated with exploited resources
[rules.reject_exploited]
priority = 4
field = [
    "connect.client-addr",
    "connect.client-name",
    "header.from",
    "header.reply-to",
    "header.sender",
    "header.received.domain",
    "header.received.ipv4",
]
match = { reputation = "exploited" }
defer = "Listed as spam source"

# Some countries where no regular contacts exist.
[lists]
bad-country = [
    "ar",
    "br",
    "mx",
    "cu",
    "cl",
    "ve",
    "co",
    "id",
    "in",
    "rs",
    "ru",
    "ua",
    "uz",
    "kz",
    "vn",
    "jp",
]
[rules.reject-country]
field = [
    "connect.client-addr.cc",
    "connect.client-name.cc",
    "envelope.mail-from.domain.cc",
    "header.sender.domain.cc",
    "header.reply-to.domain.cc",
]
match = { list = "bad-country" }
hold = "Mail from this country is likely spam"

# Reject mails where reply-to points to a privateemail.com MX (NameCheap again)
[rules.reject-privateemail]
field = "header.reply-to.domain.mx"
match = "privateemail.com"
reject = "Looks like spam (privateemail.com MX)"
